

#         Powered by TabooLib 6.0         #


Settings:
  debug: false
  # 必须小于 server.properties 中的 "view-distance"
  visible-distance: 64
  # JOIN: 当玩家加入服务器时
  # KEEP_ALIVE: 当玩家发送第一个位置数据包时
  spawn-event: KEEP_ALIVE
  # 是否在主线程上进行路径计算
  # 异步计算会带来延迟
  pathfinder-sync: true
  # 当指定的世界不存在时删除单位文件
  delete-file-in-unknown-world:
    - 'dungeon_world_1'
    - 'dungeon_world_2'
    - 'custom?'
  # 可视条件的刷新周期
  view-condition-interval: 40
  # 积分板队伍的ID
  # 启用时可改为："ady_{id}"
  team-id: DISABLED
